### ISSUE TITLE
Sending IPN _notify-validate response to domains other than www.paypal.com/cgi-bin/webscr seems to fail

### ISSUE THREAD

**Issue by tmslnz** [symphonists/paypal_payments#4]
I appears that validating the IPN against anything else than paypal.com fails. It should probably be hardcoded instead of relying on the _build_paypay_url() function.
I also couldn't find mention of sending the IPN response to any of the subdomains other than .com

Unless it was all a temporary issue with PayPal, I guess it's worth investigating as it might save some headaches around.

**Comment by makenosound** [comment]
Interesting. I remember you saying it _did_ work for a while though, did you change anything before that failed or does it seems as though PayPal have changed so their country-specific sites no longer respond to IPN?

**Comment by tmslnz** [comment]
I was in testing mode all the time :) which sends to .com no matter what country has been chosen.

**Comment by makenosound** [comment]
OK, I've looked through the PayPal docs and, though I can't find definitive evidence, they only make reference to IPNs responding at the `.com` so I've updated the extension to reflect that. Would be great if you can test it and let me know if it solves your problem.

**Comment by tmslnz** [comment]
Hey thanks, I'll clone it on the next dev iteration of the website, I had the .com hardcoded already by the time I posted the issue.

By the way, PP seems to be doing geoip based redirection already, are you sure the country targeting function is necessary at all?

**Comment by makenosound** [comment]
It may not be any more, I'll happily remove it if I can confirm that's the case.
